### ISSUE TITLE
Empty index.html file even though the json file is present and has the data in it

### ISSUE THREAD

**Issue by vikrambharadwaj** [holmari/gerritstats#15]
Hi,

I successfully ran the gerrit_stats.sh after generating the json file using gerrit_downloader.sh but the index.html remains empty, Here is the log:

./gerrit_stats.sh -f gerrit_out/sonom.json 
Warning: file 'gerrit_out/sonom.json' does not exist, skipping.
Creating overview.js
Creating datasetOverview.js
Creating ids.js
Output written to /tmp/gerritstats-master/GerritStats/out-html/data

> gerritstats@1.0.0 prewebpack /tmp/gerritstats-master/GerritStats
> mkdir -p out-html && cp src/main/frontend/index.html out-html/

> gerritstats@1.0.0 webpack /tmp/gerritstats-master/GerritStats
> webpack --display-error-details --colors --progress --config webpack.config.js

Hash: 0ab6c21e5dcb5c52313e  
Version: webpack 1.14.0
Time: 18469ms
                                 Asset     Size  Chunks             Chunk Names
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]  
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]  
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]  
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]  
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]  
  4713eef7edb06b1e8b4e1e4a6c489a5c.png  19.8 kB          [emitted]  
  a3b60647ef11633dfce07443e8ebcc56.png  19.8 kB          [emitted]  
                             bundle.js  3.12 MB       0  [emitted]  main
    + 742 hidden modules
Output generated to /tmp/gerritstats-master/out-html
 
For some reason its unable to find the json file even though I see the json file in the gerrit_out dir and has all the data in it.

**Comment by Nooba** [comment]
(Workaround) It works if you put the full path to the file.
./gerrit_stats.sh -f /Users/username/full/path/to/file.json

**Comment by vikrambharadwaj** [comment]
Yep, It worked..!! Thanks a lot for the support..!!

Regards
Vikram

**Comment by holmari** [comment]
I changed the shell script to not change paths, so the file will be correctly resolved.
