### ISSUE TITLE
Shortcuts at the top of the user page do not work

### ISSUE THREAD

**Issue by jrbyrne** [holmari/gerritstats#17]
Nothing happens when I click on the shortcuts at the top of the user page (Overall/Reviewers and approvals/Iteration/Per-month/Comments) when I generate stats for my server, although they do work on the demonstration page at https://gerritstats-demo.firebaseapp.com.

**Comment by bpangrati** [comment]
But do you see the statistics for user and the graphics?

**Comment by jrbyrne** [comment]
Yes, all the stats are there, but clicking on the shortcut buttons does nothing.
