### ISSUE TITLE
Use Mailmap  to combine multiple accounts

### ISSUE THREAD

**Issue by rasjani** [holmari/gerritstats#26]
In some cases, developers tend to have quite lax behaviour when it comes to setting up their user.name & user.email settings to the git repo they are working on.  This leads to scenarios where a single user can be shown as multiple users if she has made commits/reviews with different settings. 

Git itself has a functionality to map these cases into a single user via "mailmap" file.  See: https://git-scm.com/docs/git-shortlog#_mapping_authors - this sort of a map file is used by other tools also like gitstats ( https://github.com/hoxu/gitstats ) 

I think it would be a good feature get a author mapping also to gerritstats.

**Comment by jhansche** [comment]
I wrote a patch for this a long time ago and never submitted it, because I didn't have time to clean it up for a PR.  If you're interested in using it or taking the time to clean it up for PR: https://github.com/MeetMe/gerritstats/commit/e7776dba0ba80e532c1eb4bbbf94892d59d4154b
