### ISSUE TITLE
--exclude works only emails.

### ISSUE THREAD

**Issue by rasjani** [holmari/gerritstats#29]
I tried to originally remove few jenkins bots (making comments to gerrit reviews based on build results) from gerritstats but it didnt seem to work.  Help says following:

`    --exclude
       If specified, the comma-separated list of identities will be excluded
       from all generated statistics.
       Default: []
`
I passed "jenkins,fin-jenkins" but neither of the accounts where removed from statistics.  Fix was quite evident after browsing the javascript: exclude expects emails. 

However, in my case, one of the bot does not provide email in their gerrit messages so gerritstats is not able to remove it.

This is another usecase for supporting mailmap - bots/people who do not have proper git config setup can then be fixed/grouped into a single user during generation of the stats. See #26

**Comment by castulo** [comment]
I am having the same problem, my Jenkins bot doesn't have email. I cannot exclude it.
