### ISSUE TITLE
Can't Find files "GerritDownloader.jar" & "GerritStats.jar"

### ISSUE THREAD

**Issue by maheshpawar149** [holmari/gerritstats#30]
Hi,
 while running these scripts it tries to find JAR files but they are missing.

1. ./gerrit_stats.sh
Error: Unable to access jarfile GerritStats/build/libs/GerritStats.jar

2. ./gerrit_downloader.sh
Error: Unable to access jarfile /opt/gerrit_workspace/Gerrit_Plugins/byHolmari/gerritstats/GerritDownloader/build/libs/GerritDownloader.jar

In both paths, the build files are missing.

can you help me out
Thanks

**Comment by holmari** [comment]
Have you built the jars? `./gradlew assemble`
