### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by rinkygupta2008** [holmari/gerritstats#4]
Hi,

I have tried to execute a downloader command to get JSON data. But it failed at point of command execution , due to some permission issue.
My project is maintained at gerrit. and i have generated keys and registered to gerrit server also.
Command executed :
 ./gerrit_downloader.sh --server MyServerName --project MyProjectName --limit 10 --output-dir MyOutput/

Output :

Reading data from MyServerName:29418 for last 10 commits
ssh -p 29418 MyServerName gerrit query project:^ MyProjectName --format=JSON --all-approvals --all-reviewers --comments 
Process exited with return code 255 and output:
Permission denied (publickey).

Exception in thread "main" java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2927)
	at com.holmsted.gerrit.GerritStatsDownloaderMain.main(GerritStatsDownloaderMain.java:35)

**Comment by holmari** [comment]
I fixed the exception now, thanks for that.

Your problem is different however - either your ~/.ssh/config is incorrect or your keys are not valid.

**Comment by rinkygupta2008** [comment]
Thanks for response. Its working now.
