### ISSUE TITLE
Out-html page "Users in analysis" data exception when running gerrit_stats.sh

### ISSUE THREAD

**Issue by yajunzhi** [holmari/gerritstats#70]
After json data created by GerritStatsDownloader, then execute gerrit_stats.sh, but the out-html displacedall “Anonymous Coward” in  “Users in analysis ”, while the name info in Overview item are all correct.
How to change the configure or settings?

**Comment by holmari** [comment]
As mentioned in the readme, this tool is unmaintained. I'm happy to accept pull requests to `repostats` which implements this analytics tool for GitHub.
