### ISSUE TITLE
Execution failed for task ':GerritCommon:compileJava'.

### ISSUE THREAD

**Issue by anujsadani** [holmari/gerritstats#8]
while executing ./gradlew assemble getting BUILD FAILED.

/home/username/gerritstats-master/GerritCommon/src/main/java/com.holmsted/resources/ResourceReader.java:21: illegal start of type
        List<String> lines = new ArrayList<>();
                                           ^
2 errors
:GerritCommon:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':GerritCommon:compileJava'.
> Compilation failed; see the compiler error output for details.

**Comment by holmari** [comment]
You're trying to compile with an old Java version. Java 8 is required for this project. I will add a mention about it to the README.
